project:
  type: manuscript
manuscript:
  article: kart_tutorial.qmd
  meca-bundle: kart_tutorial.zip
format:
  html:
    embed-resources: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf-agu: default
execute:
  freeze: true



